[package]
name = "toolchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = { optional = true }
anyhow = {}

[features]
build-faiss = [ "cmake" ]
build-tensorflow = []